# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goit < Formula
  desc "A simple text editor with multiple window."
  homepage "https://github.com/dragno99/goit"
  version "0.1.0"

  on_macos do
    url "https://github.com/dragno99/goit/releases/download/v0.1.0/goit_0.1.0_darwin_amd64.tar.gz"
    sha256 "ad2e97d999ddce9b80e75af17b14f6d8eb179d1be0068c3f0d6ebebda318440f"

    def install
      bin.install "goit"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Goit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dragno99/goit/releases/download/v0.1.0/goit_0.1.0_linux_amd64.tar.gz"
      sha256 "a7fc0c8e03f6e5d7e0256597b9999945cd179c37e3ed7f08ca94f96c24bcf76d"

      def install
        bin.install "goit"
      end
    end
  end
end
